# Generated by Django 4.2.7 on 2023-11-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_home_button_link_home_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
