# Generated by Django 4.2.7 on 2023-11-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_alter_home_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
